-- MySQL Script generated by MySQL Workbench
-- 07/09/14 11:12:33
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema itdevelc_pdeb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `itdevelc_pdeb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `itdevelc_pdeb` ;

-- -----------------------------------------------------
-- Table `itdevelc_pdeb`.`Departamentos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `itdevelc_pdeb`.`Departamentos` (
  `idDepartamento` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NULL,
  `descripcion` VARCHAR(200) NULL,
  PRIMARY KEY (`idDepartamento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `itdevelc_pdeb`.`Usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `itdevelc_pdeb`.`Usuarios` (
  `idUsuario` INT NOT NULL AUTO_INCREMENT,
  `contrasena` VARCHAR(20) NULL,
  `nombre` VARCHAR(100) NOT NULL,
  `correo` VARCHAR(50) NULL,
  `tipoUsuario` INT NULL,
  `Departamentos_idDepartamento` INT NOT NULL,
  PRIMARY KEY (`idUsuario`),
  INDEX `fk_Usuarios_Departamentos1_idx` (`Departamentos_idDepartamento` ASC),
  CONSTRAINT `fk_Usuarios_Departamentos1`
    FOREIGN KEY (`Departamentos_idDepartamento`)
    REFERENCES `itdevelc_pdeb`.`Departamentos` (`idDepartamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `itdevelc_pdeb`.`Universidades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `itdevelc_pdeb`.`Universidades` (
  `idUniversidad` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NULL,
  `mision` VARCHAR(200) NULL,
  `vision` VARCHAR(200) NULL,
  `direccion` VARCHAR(150) NULL,
  `comoLlegar` VARCHAR(200) NULL,
  `contacto` VARCHAR(100) NULL,
  `telefono1` VARCHAR(15) NULL,
  `telefono2` VARCHAR(15) NULL,
  `correo` VARCHAR(50) NULL,
  `sitioWeb` VARCHAR(100) NULL,
  `logotipo` VARCHAR(200) NULL,
  `status` INT NOT NULL,
  `servicioMyV` INT NOT NULL,
  `Usuarios_idUsuario` INT NOT NULL,
  PRIMARY KEY (`idUniversidad`),
  INDEX `fk_Universidades_Usuarios1_idx` (`Usuarios_idUsuario` ASC),
  CONSTRAINT `fk_Universidades_Usuarios1`
    FOREIGN KEY (`Usuarios_idUsuario`)
    REFERENCES `itdevelc_pdeb`.`Usuarios` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `itdevelc_pdeb`.`Apoyos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `itdevelc_pdeb`.`Apoyos` (
  `idApoyo` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NULL,
  `proveedor` VARCHAR(100) NULL,
  `objetivo` VARCHAR(200) NULL,
  `convocatoria` VARCHAR(200) NULL,
  `logotipo` VARCHAR(200) NULL,
  `status` INT NULL,
  `Departamentos_idDepartamento` INT NOT NULL,
  `Usuarios_idUsuario` INT NOT NULL,
  PRIMARY KEY (`idApoyo`, `Departamentos_idDepartamento`, `Usuarios_idUsuario`),
  INDEX `fk_Apoyos_Departamentos1_idx` (`Departamentos_idDepartamento` ASC),
  INDEX `fk_Apoyos_Usuarios1_idx` (`Usuarios_idUsuario` ASC),
  CONSTRAINT `fk_Apoyos_Departamentos1`
    FOREIGN KEY (`Departamentos_idDepartamento`)
    REFERENCES `itdevelc_pdeb`.`Departamentos` (`idDepartamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Apoyos_Usuarios1`
    FOREIGN KEY (`Usuarios_idUsuario`)
    REFERENCES `itdevelc_pdeb`.`Usuarios` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `itdevelc_pdeb`.`Publicidad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `itdevelc_pdeb`.`Publicidad` (
  `idPublicidad` INT NOT NULL AUTO_INCREMENT,
  `imagen` VARCHAR(200) NULL,
  `descripcion` VARCHAR(200) NULL,
  `liga` VARCHAR(100) NULL,
  `Usuarios_idUsuario` INT NOT NULL,
  PRIMARY KEY (`idPublicidad`, `Usuarios_idUsuario`),
  INDEX `fk_Publicidad_Usuarios1_idx` (`Usuarios_idUsuario` ASC),
  CONSTRAINT `fk_Publicidad_Usuarios1`
    FOREIGN KEY (`Usuarios_idUsuario`)
    REFERENCES `itdevelc_pdeb`.`Usuarios` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `itdevelc_pdeb`.`Carreras`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `itdevelc_pdeb`.`Carreras` (
  `idCarrera` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NULL,
  `objetivo` VARCHAR(200) NULL,
  `perfilIngreso` VARCHAR(200) NULL,
  `perfilEgreso` VARCHAR(200) NULL,
  `campo` VARCHAR(200) NULL,
  `alumnosDisponibles` INT NULL,
  `Universidades_idUniversidad` INT NOT NULL,
  PRIMARY KEY (`idCarrera`, `Universidades_idUniversidad`),
  INDEX `fk_Carreras_Universidades1_idx` (`Universidades_idUniversidad` ASC),
  CONSTRAINT `fk_Carreras_Universidades1`
    FOREIGN KEY (`Universidades_idUniversidad`)
    REFERENCES `itdevelc_pdeb`.`Universidades` (`idUniversidad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `itdevelc_pdeb`.`Empresas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `itdevelc_pdeb`.`Empresas` (
  `idEmpresa` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `descripcion` VARCHAR(200) NULL,
  `mision` VARCHAR(200) NULL,
  `vision` VARCHAR(200) NULL,
  `productos` VARCHAR(200) NULL,
  `direccion` VARCHAR(150) NULL,
  `comoLlegar` VARCHAR(200) NULL,
  `contacto` VARCHAR(100) NULL,
  `telefono1` VARCHAR(15) NULL,
  `telefono2` VARCHAR(15) NULL,
  `correo` VARCHAR(50) NULL,
  `sitioWeb` VARCHAR(100) NULL,
  `antiguedad` INT NULL,
  `numeroEmpleados` INT NULL,
  `logotipo` VARCHAR(200) NULL,
  `status` INT NOT NULL,
  `Usuarios_idUsuario` INT NOT NULL,
  PRIMARY KEY (`idEmpresa`),
  INDEX `fk_Empresas_Usuarios1_idx` (`Usuarios_idUsuario` ASC),
  CONSTRAINT `fk_Empresas_Usuarios1`
    FOREIGN KEY (`Usuarios_idUsuario`)
    REFERENCES `itdevelc_pdeb`.`Usuarios` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `itdevelc_pdeb`.`Vinculacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `itdevelc_pdeb`.`Vinculacion` (
  `Universidades_idUniversidades` INT NOT NULL,
  `Empresas_idEmpresas` INT NOT NULL,
  `Apoyos_idApoyos` INT NOT NULL,
  `Usuarios_idUsuario` INT NOT NULL,
  `necesidad` VARCHAR(200) NULL,
  `propuesta` VARCHAR(200) NULL,
  PRIMARY KEY (`Universidades_idUniversidades`, `Empresas_idEmpresas`, `Apoyos_idApoyos`, `Usuarios_idUsuario`),
  INDEX `fk_Universidades_has_Empresas_Empresas1_idx` (`Empresas_idEmpresas` ASC),
  INDEX `fk_Universidades_has_Empresas_Universidades1_idx` (`Universidades_idUniversidades` ASC),
  INDEX `fk_Vincular_Apoyos1_idx` (`Apoyos_idApoyos` ASC),
  INDEX `fk_Vinculacion_Usuarios1_idx` (`Usuarios_idUsuario` ASC),
  CONSTRAINT `fk_Universidades_has_Empresas_Universidades1`
    FOREIGN KEY (`Universidades_idUniversidades`)
    REFERENCES `itdevelc_pdeb`.`Universidades` (`idUniversidad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Universidades_has_Empresas_Empresas1`
    FOREIGN KEY (`Empresas_idEmpresas`)
    REFERENCES `itdevelc_pdeb`.`Empresas` (`idEmpresa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Vincular_Apoyos1`
    FOREIGN KEY (`Apoyos_idApoyos`)
    REFERENCES `itdevelc_pdeb`.`Apoyos` (`idApoyo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Vinculacion_Usuarios1`
    FOREIGN KEY (`Usuarios_idUsuario`)
    REFERENCES `itdevelc_pdeb`.`Usuarios` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `itdevelc_pdeb`.`RegistrosApoyos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `itdevelc_pdeb`.`RegistrosApoyos` (
  `Apoyos_idApoyo` INT NOT NULL,
  `Usuarios_idUsuario` INT NOT NULL,
  PRIMARY KEY (`Apoyos_idApoyo`, `Usuarios_idUsuario`),
  INDEX `fk_Apoyos_has_Usuarios_Usuarios1_idx` (`Usuarios_idUsuario` ASC),
  INDEX `fk_Apoyos_has_Usuarios_Apoyos1_idx` (`Apoyos_idApoyo` ASC),
  CONSTRAINT `fk_Apoyos_has_Usuarios_Apoyos1`
    FOREIGN KEY (`Apoyos_idApoyo`)
    REFERENCES `itdevelc_pdeb`.`Apoyos` (`idApoyo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Apoyos_has_Usuarios_Usuarios1`
    FOREIGN KEY (`Usuarios_idUsuario`)
    REFERENCES `itdevelc_pdeb`.`Usuarios` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `itdevelc_pdeb`.`Vacantes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `itdevelc_pdeb`.`Vacantes` (
  `cantidad` INT NOT NULL,
  `descripcion` VARCHAR(250) NULL,
  `Empresas_idEmpresa` INT NOT NULL,
  PRIMARY KEY (`cantidad`, `Empresas_idEmpresa`),
  INDEX `fk_Vacantes_Empresas1_idx` (`Empresas_idEmpresa` ASC),
  CONSTRAINT `fk_Vacantes_Empresas1`
    FOREIGN KEY (`Empresas_idEmpresa`)
    REFERENCES `itdevelc_pdeb`.`Empresas` (`idEmpresa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `itdevelc_pdeb`.`OpcionesVinculacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `itdevelc_pdeb`.`OpcionesVinculacion` (
  `idOpcion` INT NOT NULL,
  `descripcion` VARCHAR(100) NULL,
  `Universidades_idUniversidad` INT NOT NULL,
  PRIMARY KEY (`idOpcion`, `Universidades_idUniversidad`),
  INDEX `fk_OpcionesVinculacion_Universidades1_idx` (`Universidades_idUniversidad` ASC),
  CONSTRAINT `fk_OpcionesVinculacion_Universidades1`
    FOREIGN KEY (`Universidades_idUniversidad`)
    REFERENCES `itdevelc_pdeb`.`Universidades` (`idUniversidad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `itdevelc_pdeb`.`Configuracion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `itdevelc_pdeb`.`Configuracion` (
  `correoAvisos` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`correoAvisos`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

